### ISSUE TITLE
Rules in README

### ISSUE THREAD

**Issue by oscar-h64** [fpclass/perpetual-haskelling-initiative#11]
It would be good to get all the rules and specifics on how the game is going to work written up in the `README` so we can reference it while coding

**Comment by lynchgeorge** [comment]
I think ive done this is feature/readme, im just adding examples of cards now. Maybe worth closing this. If there are any gaps in the rules I may have missed please let me know and ill sort it out asap!

**Comment by oscar-h64** [comment]
It should close itself once PR #12 is closed, that's currently awaiting another review. I don't mind doing it but it's already got people assigned so I'm not sure if I should step on their toes

**Comment by lynchgeorge** [comment]
Its all good I can add you, it shouldnt be a problem. Any ideas for python cards by the way, not too familiar with the language.

Update: just checked and someone else reviewed it so its all good 👍

**Comment by ghost** [comment]
A couple ideas for python. Could have a 'white space' minion or something like that.
It's been a while since I have done python programming but one thing with it that I remember is that variables generally don't have specific type and the lists can have different types of data in them so maybe it could focus on spells which can effect any kind of minion or change the type of it or something like that?
Another idea is maybe lots of fast and cheap minions as it is quite quick to write a program with?

**Comment by lynchgeorge** [comment]
Sounds great! Ill add them in!
